object Versions {
    const val ktLintVersion = "0.33.0"
    const val mockito3Version = "3.3.3"
    const val navigationCompose = "2.5.0-alpha01"
    const val coil = "1.4.0"
    const val composeActivity = "1.3.1"
    const val lifeCycleRuntime = "2.3.1"
    const val coreKtx = "1.7.0"
    const val appcompat = "1.3.0"
    const val jUnit = "4.13.2"
    const val material = "1.5.0"
    const val koin = "3.0.1"
    const val retrofit = "2.9.0"
    const val coroutines = "1.6.0"
    const val composeVersion = "1.0.1"
    const val googleSwipeRefresh = "0.15.0"
    const val paging = "3.1.0"
    const val pagingCompose = "1.0.0-alpha14"
}